AllCops:
  Include:
    - Rakefile
  Exclude:
    - bin/**/*

Layout/DotPosition:
  EnforcedStyle: leading

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Lint/ScriptPermission:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - flag-icons-rails.gemspec

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
